[package]
name = "chopper"
version = "0.1.0"
authors = ["rombar <rombar@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = """
Example usage logging roller, and combine it with other logger
"""
keywords = ["logging"]

[dependencies]
log = "0.4.8"
log4rs = "0.13.0"